updated trading partner endpoint
WeInfuse/change_health pull request #70
Opened 2023-08-24 20:49 UTC by Btace13

Updated Endpoint for trading_partner request.

- updated endpoint on trading_partner
- updated params on trading_partner to only return Eligibility service types
- updated mapping on trading_partner_data for new response from endpoint
- removed medical_eligibility_enabled from trading_partners_data
- updated tests

2023-08-24 21:37 UTC, vechema requested changes
These changes are breaking backwards compatibility. You need to either go to version v5.0.0 or maintain backwards compatibility

2023-08-24 21:37 UTC, vechema commented on CHANGELOG.md
> +# [4.13.2] - 2022-08-24
At the bottom of the file, need a line like but with the new version

`[4.13.1]: https://github.com/WeInfuse/change_health/compare/v4.13.0...v4.13.1`

2023-08-25 21:19 UTC, vechema approved these changes
![lgtm](https://media.giphy.com/media/lrDMG46JjKiovLbkn8/giphy.gif)

2023-08-29 21:28 UTC, acrodriguez requested changes
Merge conflicts and one change addition to CHANGELOG

2023-08-29 21:28 UTC, acrodriguez commented on CHANGELOG.md
> +* **breaking:** removed medical_eligibility_service_id from trading_partner_data
```suggestion
* **breaking:** removed medical_eligibility_service_id from trading_partner_data
* **breaking:** removed medical_eligibility_service from trading_partner_data
```

2023-08-29 22:00 UTC, acrodriguez approved these changes

2023-08-30 15:07 UTC, merged