enrique/186327628-adding-clearing-house-query-param-to-trading-partner
WeInfuse/change_health pull request #75
Opened 2023-10-25 19:16 UTC by Btace13

Added clearingHouse param to Trading Partner query

2023-10-25 21:49 UTC, AkaKuro4Ever approved these changes
![giphy](https://media1.giphy.com/media/XAdbHJywVjF5K/giphy.gif?cid=6104955ed71mq0d351672npv8ymuunzpfttpavcxnr20bp13&ep=v1_gifs_translate&rid=giphy.gif&ct=g)

2023-10-27 15:46 UTC, acrodriguez requested changes

2023-10-27 15:46 UTC, acrodriguez commented on lib/change_health/request/trading_partner.rb
> +          clearingHouse: 'dbq'
Not a patch as this changes underlying expectation of query results.

2023-10-27 20:27 UTC, acrodriguez approved these changes
Approving merge to match already published gem change

2023-10-27 20:29 UTC, merged